config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"

  resources :events do
    collection do
      post :attend_event
    end

    member do
      delete :leave_event
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events
  has_many :users, through: :user_events

  belongs_to :user

  enum event_type: { workshop: 'Work Shop', seminar: 'Seminar', conference: 'Conference', reunions: 'Reunions', party: 'Party' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :user_events
  has_many :events, through: :user_events

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum gender: { male: 'Male', female: 'Female' }
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index,:show]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :leave_event]

  def index
    @events = Event.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  def attend_event
    event = Event.find(params[:event_id])
    user_event = event.user_events.create(user_id: current_user.id, booking_date: Time.now)

    if user_event
      redirect_to event_path(event), notice: 'User was successfully registered.'
    else
      redirect_to event_path(event), notice: 'User was not successfully registered.'
    end
  end

  def leave_event
    current_user.user_events.find_by(event_id: @event.id).destroy
    redirect_to event_path(@event), notice: 'User was successfully unregistered.'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:user_id, :title, :event_type, :start_time, :end_time, :description, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def already_registered?(event)
    'disabled' if current_user.user_events.find_by(event_id: event.id).present?
  end

  def allow_leave(user_id)
    'disabled' unless current_user.id == user_id
  end

  def show_cost(cost)
    (cost - ((cost * 5) / 100))
  end

  def get_benefit(cost)
    ((cost * 5) / 100)
  end

  def is_event_closed?(event)
    Time.parse(event.end_time.strftime("%Y-%m-%d %H:%M")) > Time.now
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <div class="form-group">
    <div class="row">
      <%= form.hidden_field :user_id, :value => current_user.id %>
      <div class="col-md-4">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control', required: true %>
      </div>
      <div class="col-md-4">
        <%= form.label :event_type %>
        <%= form.select :event_type, options_for_select(Event.event_types.values), { required: true }, { class: 'form-control' } %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-md-4">
        <%= form.label :start_time %>
        <div class='input-group date' id='start-time'>
          <%= form.text_field :start_time, class: "form-control", required: true %>
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </div>
      </div>
      <div class="col-md-4">
        <%= form.label :end_time %>
        <div class='input-group date' id='end-time'>
          <label ></label>
          <%= form.text_field :end_time, class: "form-control", id: "show-error", title: "End Time should be greater than Start Time", required: true %>
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-md-4">
        <%= form.label :cost %>
        <%= form.text_field :cost, class: 'form-control', required: true %>
      </div>
      <div class="col-md-4">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-md-4">
        <%= form.submit "Submit", class: 'btn btn-primary', id: 'submit-form' %>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#start-time').datetimepicker({
      format: "DD-MM-YYYY h:mm A",
      minDate: new Date()
    });
    
    $('#end-time').datetimepicker({
      minDate: new Date(),
      format: "DD-MM-YYYY h:mm A",
    });

    $('#end-time').datetimepicker().on('dp.change', function (event) {
      var fromDate = $('#start-time').data("DateTimePicker").date()._d;
      var toDate = $('#end-time').data("DateTimePicker").date()._d;

      if (toDate < fromDate) {
        $("#submit-form").attr("disabled", true);
        $('#show-error').tooltip("show");
      } else {
        $("#submit-form").attr("disabled", false);
        $('#show-error').tooltip("hide");
      }
    }); 
  });
</script>

<style type="text/css">
    #show-error + .tooltip > .tooltip-inner { background-color: #f00; }
    #show-error + .tooltip > .tooltip-arrow { border-bottom-color: #f00; }
</style>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event, class: 'btn btn-primary' %>
<%= link_to 'Back', events_path, class: 'btn btn-primary' %>

app/views/events/index.html.erb
<h1>Events</h1>

<table class="table table-striped table-bordered table-hover table-sm" id="events">
  <thead class="thead-light">
    <tr>
      <th class="text-center">Title</th>
      <th class="text-center">Event type</th>
      <th class="text-center">Description</th>
      <th class="text-center">Cost</th>
      <th class="text-center">Status</th>
      <th class="text-center" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.event_type %></td>
        <td><%= event.description %></td>
        <td><%= event.cost %></td>
        <td id="event-tracker-<%= event.id %>" class="text-danger" start-time="<%= event.start_time %>" end-time="<%= event.end_time %>" event-id="<%= event.id %>"></td>
        <td><%= link_to 'Show', event, class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_event_path(event), class: "btn btn-primary btn-sm edit-#{event.id}" %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary destroy-#{event.id} btn-sm actions-#{event.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class: 'btn btn-primary' %>

<script type="text/javascript">
  $(document).ready(function(){
    function calculateTime(distance) {
      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);

      return { days: days, hours: hours, minutes: minutes, seconds: seconds }
    }

    function convertTimeToUtc(time) {
      var lastIndex = time.lastIndexOf(" ");
      time = time.substring(0, lastIndex);
      return time.toString();
    }

    $("#events tbody tr").each(function () {
      var currentRow=$(this);
      var startTime = currentRow.find("td:eq(4)").attr('start-time');
      var endTime = currentRow.find("td:eq(4)").attr('end-time');
      var eventId = currentRow.find("td:eq(4)").attr('event-id');
      startTime = convertTimeToUtc(startTime);
      endTime = convertTimeToUtc(endTime);
      time = Date.parse(startTime) > new Date ? startTime : endTime
      var countDownDate = new Date(time.replace(/\-/g, "/")).getTime();

      var x = setInterval(function() {
        var now = new Date().getTime();
        var distance = countDownDate - now;
        result = calculateTime(distance)
        status = Date.parse(startTime) > new Date ? 'Starts In' : 'Ends In'

        $(`#event-tracker-${eventId}`).html(`${status}: ` + result['days'] + "d " + result['hours'] + "h " + result['minutes'] + "m " + result['seconds'] + "s")

        if ((Date.parse(endTime) > new Date) && (Date.parse(startTime) < new Date)) {
          $(`.destroy-${eventId}`).addClass("disabled", true);
          $(`.edit-${eventId}`).addClass("disabled", true);
        }

        if (Date.parse(endTime) < new Date) {
          $(`.destroy-${eventId}`).removeClass("disabled");
          $(`.edit-${eventId}`).addClass("disabled", true);
        }

        if (distance < 0 ) {
          $(`#event-tracker-${eventId}`).html('Closed');
        }
      }, 1000);
    });
  });
</script>

app/views/events/new.html.erb
<h3>New Event</h3>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class: 'btn btn-primary' %>

app/views/events/show.html.erb
</br></br>
<div class="row">
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-3"><b>Created By:</b></div>
      <div class="col-md-9"><%= @event.user.name %></div>
    </div></br>
    <div class="row">
      <div class="col-md-3"><b>Title:</b></div>
      <div class="col-md-9"><%= @event.title %></div>
    </div></br>

    <div class="row">
      <div class="col-md-3"><b>Event type:</b></div>
      <div class="col-md-9"><%= @event.event_type %></div>
    </div></br>

    <div class="row">
      <div class="col-md-3"><b>Start time:</b></div>
      <div class="col-md-9"><%= @event.start_time %></div>
    </div></br>

    <div class="row">
      <div class="col-md-3"><b>End time:</b></div>
      <div class="col-md-9"><%= @event.end_time %></div>
    </div></br>

    <div class="row">
      <div class="col-md-3"><b>Description:</b></div>
      <div class="col-md-9"><%= @event.description %></div>
    </div></br>

    <div class="row">
      <div class="col-md-3"><b>Cost:</b></div>
      <% if current_user.nil? || current_user.male? %>
        <div class="col-md-9">&#x20B9;<%= @event.cost %></div>
      <% else %>
        <div class="col-md-9">
          <p>&#x20B9;<%= show_cost(@event.cost) %> <del>&#x20B9;<%= @event.cost %></del></p>
          <p>You Save: &#x20B9;<%= get_benefit(@event.cost) %>(5%)</p>
        </div>
      <% end %>
    </div></br>

    <div>
      <% if current_user && !already_registered?(@event) && is_event_closed?(@event) %>
        <% unless (current_user.id == @event.user_id) %>
          <%= link_to "Attend Event", attend_event_events_path(event_id: @event.id), method: :post, class: "btn btn-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <% if current_user && @event.users.present? %>
      <h3>Participants</h3>
      <table class="table table-striped table-bordered table-hover table-sm">
        <thead class="thead-light">
          <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Leave Event</th>
          </tr>
        </thead>

        <tbody>
          <% @event.users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.gender %></td>
              <td>
                <%=  link_to "Leave", leave_event_event_path(@event), method: :delete, class: "btn btn-primary #{allow_leave(user.id)}" %>    
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div></br>


<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' %>
<%= link_to 'Back', events_path, class: 'btn btn-primary'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div>
	  	<div>
	  		<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
	  			<div class="container">
	  				<div class="row">
	  					<div class="col-md-10">
	  						<a  href="#"></a>
	  						<%= link_to 'Home', events_path, class: "navbar-brand" %>
	  					</div>
	  					<div class="col-md-2" id="link">
	  						<% if current_user %>
	  							<label><%= current_user.name %></label>&nbsp;
	  							<%= link_to 'Logout', destroy_user_session_path, method: :delete %> 
	  						<% else %>
	  							<%= link_to 'Login', new_user_session_path %>&nbsp;
	  						<% end %>
	  					</div>
	  				</div>
	  			</div>
				</nav>
	  	</div>
	  	<div class="container">
	  		<div class="flash_messages">
		      <% if alert %>
		        <div class='alert alert-danger alert-dismissible'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><%= flash[:alert] %></div>
		      <% elsif notice %>
		        <div class='alert alert-success alert-dismissible'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><%= flash[:notice] %></div>
		      <% end %>
		    </div>
	    	<%= yield %>
	  	</div>
	  </div>
  </body>
</html>